"""Generate Clash Node Pilot's raster icon candidates and packaged icons."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import math

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "packaging" / "icons"
OUT.mkdir(parents=True, exist_ok=True)
SIZE = 1024

def font(size):
    for name in ("segoeui.ttf", "Arial.ttf", "DejaVuSans.ttf"):
        try:
            return ImageFont.truetype(name, size)
        except OSError:
            pass
    return ImageFont.load_default()

def base(bg):
    return Image.new("RGBA", (SIZE, SIZE), bg)

def rounded(draw, box, radius, fill):
    draw.rounded_rectangle(box, radius=radius, fill=fill)

def candidate_orbit():
    im = base((16, 25, 40, 255)); d = ImageDraw.Draw(im)
    rounded(d, (70, 70, 954, 954), 190, (25, 42, 64, 255))
    cx = cy = 512
    d.ellipse((245, 245, 779, 779), outline=(76, 212, 190, 255), width=34)
    d.arc((185, 185, 839, 839), 205, 350, fill=(250, 184, 73, 255), width=34)
    for x, y, c in ((512, 210, (250,184,73,255)), (788, 512, (76,212,190,255)), (512,814,(238,108,126,255))):
        d.ellipse((x-45,y-45,x+45,y+45), fill=c)
    d.ellipse((cx-102, cy-102, cx+102, cy+102), fill=(238,108,126,255))
    d.ellipse((cx-38, cy-38, cx+38, cy+38), fill=(255,238,220,255))
    return im

def candidate_prism():
    im = base((243, 245, 242, 255)); d = ImageDraw.Draw(im)
    rounded(d, (70, 70, 954, 954), 190, (255, 255, 250, 255))
    # A clean route through three nodes, with a folded prism as the mark.
    pts = [(260, 704), (512, 512), (764, 320)]
    d.line(pts, fill=(24, 72, 91, 255), width=42, joint="curve")
    d.line([(260,704),(512,704),(764,320)], fill=(250, 156, 66, 255), width=15, joint="curve")
    for x, y in pts:
        d.ellipse((x-74,y-74,x+74,y+74), fill=(24,72,91,255), outline=(255,255,250,255), width=18)
        d.ellipse((x-22,y-22,x+22,y+22), fill=(250,156,66,255))
    d.polygon([(512, 270), (634, 342), (512, 414), (390,342)], fill=(56, 164, 154, 255))
    d.polygon([(512, 270), (634, 342), (512, 342)], fill=(250, 156, 66, 255))
    return im

def candidate_compass():
    im = base((37, 30, 57, 255)); d = ImageDraw.Draw(im)
    rounded(d, (70, 70, 954, 954), 190, (58, 44, 80, 255))
    d.ellipse((180,180,844,844), outline=(222, 231, 245, 255), width=22)
    d.ellipse((280,280,744,744), outline=(110, 219, 196, 255), width=13)
    d.polygon([(512, 185), (596, 512), (512, 839), (428,512)], fill=(238, 108, 126, 255))
    d.polygon([(512, 185), (596,512), (512,512)], fill=(255, 193, 83, 255))
    d.ellipse((466,466,558,558), fill=(110,219,196,255), outline=(255,255,255,255), width=12)
    return im

candidates = {"orbit": candidate_orbit(), "prism": candidate_prism(), "compass": candidate_compass()}
for name, image in candidates.items():
    image.save(OUT / f"candidate-{name}.png", "PNG", optimize=True)

default = candidates["prism"]
default.save(OUT / "clash-node-pilot.ico", sizes=[(16,16),(24,24),(32,32),(48,48),(64,64),(128,128),(256,256)])
default.save(OUT / "ClashNodePilot.icns", format="ICNS")

thumb = 320
sheet = Image.new("RGB", (thumb * 3, 390), (232, 235, 232))
sd = ImageDraw.Draw(sheet)
for i, (name, image) in enumerate(candidates.items()):
    sheet.paste(image.convert("RGB").resize((thumb, thumb), Image.Resampling.LANCZOS), (i*thumb, 0))
    label = f"{name} {'(default)' if name == 'prism' else ''}".strip()
    sd.text((i*thumb + 18, 340), label, fill=(28, 39, 46), font=font(25))
sheet.save(OUT / "icon-candidates.png", "PNG", optimize=True)

(OUT / "README.md").write_text("""# Clash Node Pilot icon candidates\n\nGenerated by `scripts/generate-icons.py` using Pillow. The three directions are:\n\n- **Orbit**: service nodes around a stable core.\n- **Prism**: a routed path and folded prism; selected default for packaging.\n- **Compass**: a directional navigation mark for connectivity and control.\n\n`clash-node-pilot.ico` and `ClashNodePilot.icns` are generated from the Prism direction at native multi-size resolutions. Run the generator again after changing the artwork.\n""", encoding="utf-8")
